name: Push run bun

on:
    push:

jobs:
    test-action:
        name: Test the action now
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            # run any `bun` or `bunx` command
            - run: bun install
            - run: bun ./local_test.ts
            # - run: bun run build
