name: Test action
on:
<<<<<<< HEAD
  push:
    branches: "main"
  pull_request:
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jcbhmr/configure-bun-action@v1
      - uses: ./
=======
    workflow_dispatch:
        inputs:
            filename:
                type: string
                description: "The filename containing the individual sboms of the SVS-repos"
                required: true
            repos:
                type: string
                description: "Comma-separated list of repositories and their versions {repo}@{version}"
                required: true

jobs:
    test-action:
        name: Test the action now
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm install
            - run: node ./dist/index.js
>>>>>>> 731b43b (u9)
